import Head from "next/head";
// import Navbar from "../Navbar/Navbar";
export default function Layout({ children, title = "CryptoCoins" }) {
  const Navbar = () => {
    return (
      <nav className=" bg-secondary h-screen w-60">
        <div className="container-fluid w-full flex items-center justify-between">
          <div className="container-fluid">Fission Crypto</div>
        </div>
      </nav>
    );
  };

  return (
    <div className="flex  bg-primary ">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="h-screen gap-10 flex-auto  flex flex-col">
        <div className=" w-full h-32  shadow-md flex  items-center justify-between">
          Fussion
        </div>
        <main className="grow overflow-y-scroll  mx-5">{children}</main>
      </div>
    </div>
  );
}
